# Generated by Django 5.1.6 on 2026-03-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltaster',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('generation_failed', 'Generation Failed')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='journey_stage',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('generating_paths', 'Generating Paths'), ('career_discovery', 'Career Discovery'), ('skill_taster', 'Skill Taster')], default='onboarding', max_length=20),
        ),
    ]
