# Generated by Django 5.1.6 on 2026-03-22 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='journey_stage',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('career_discovery', 'Career Discovery'), ('skill_taster', 'Skill Taster')], default='onboarding', max_length=20),
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('estimated_timeline_months', models.IntegerField()),
                ('salary_range', models.JSONField(default=dict)),
                ('match_reasoning', models.TextField()),
                ('relevance_score', models.FloatField()),
                ('is_selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_paths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_paths',
            },
        ),
    ]
