# Generated by Django 5.1.15 on 2026-03-22 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_careerpath'),
        ('api', '0003_userprofile_journey_stage_careerpath'),
    ]

    operations = [
    ]
