# Generated by Django 5.1.6 on 2026-03-22 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20260322_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('taster_content', models.JSONField(default=dict)),
                ('assessment', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_tasters', to='api.careerpath')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tasters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skill_tasters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TasterResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_id', models.CharField(max_length=50)),
                ('user_response', models.TextField()),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill_taster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.skilltaster')),
            ],
            options={
                'db_table': 'taster_responses',
                'unique_together': {('skill_taster', 'module_id')},
            },
        ),
    ]
