# Generated by Django 5.1.15 on 2026-03-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_roi_data_to_careerpath'),
        ('api', '0005_skilltaster_tasterresponse'),
    ]

    operations = [
    ]
